name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test.py
      id: test-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test.py
        setup-command: sudo -H pip3 install unittest
        command: python -m unittest test.py
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-PY_RESULTS: "${{steps.test-py.outputs.result}}"
      with:
        runners: test-py
